# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1174, 680)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #1c1c1c; /* Dark gray background */")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("/* Apply to the entire application */\n"
"QWidget {\n"
"    background-color: #1c1c1c; /* Dark gray background */\n"
"    color: #f0f0f0; /* Light text color */\n"
"\n"
"}\n"
"\n"
"/* Apply to labels */\n"
"QLabel {\n"
"    color: #f44336; /* Bright red text color */\n"
"    font-size: 16px; /* Adjusted font size for labels */\n"
"    padding: 5px; /* Add padding for labels */\n"
"}\n"
"\n"
"/* Apply to buttons */\n"
"QPushButton {\n"
"    background-color: #d32f2f; /* Bright red background */\n"
"    border: none; /* No border */\n"
"    color: #ffffff; /* White text color */\n"
"    padding: 10px 20px; /* Padding inside the button */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Adjust font size */\n"
"    margin: 5px; /* Margin around buttons */\n"
"    transition: background-color 0.3s ease; /* Smooth transition */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e53935; /* Slightly brighter red on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Darker red when pressed */\n"
"}\n"
"\n"
"/* Apply to form frame */\n"
"QFrame#formFrame {\n"
"    background-color: #2e2e2e; /* Slightly lighter gray for formFrame */\n"
"    border: 2px solid #d32f2f; /* Bright red border */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    padding: 15px; /* Padding inside the frame */\n"
"    margin: 10px; /* Margin around frame */\n"
"}\n"
"\n"
"/* Apply to tab widget */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #d32f2f; /* Bright red border around tab pane */\n"
"    background-color: #1c1c1c; /* Dark background for tab pane */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 10px; /* Padding inside the tab pane */\n"
"}\n"
"\n"
"\n"
"QTabBar::tab {\n"
"    background: #2e2e2e; /* Dark gray background for tabs */\n"
"    color: #f0f0f0; /* Light text color */\n"
"    border: 1px solid #d32f2f; /* Bright red border */\n"
"    border-bottom-color: #1c1c1c; /* Same as pane background to blend */\n"
"    border-radius: 5px 5px 0 0; /* Rounded top corners */\n"
"    padding: 8px 16px; /* Padding inside tabs */\n"
"    margin: 2px; /* Margin between tabs */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #d32f2f; /* Bright red background for selected tab */\n"
"    color: #ffffff; /* White text color for selected tab */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: #e53935; /* Slightly brighter red on hover */\n"
"}\n"
"\n"
"/* Optional: Style for QLineEdit, QComboBox, etc. */\n"
"QLineEdit, QComboBox {\n"
"    background-color: #3e3e3e; /* Dark gray background */\n"
"    border: 1px solid #d32f2f; /* Bright red border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    color: #f0f0f0; /* Light text color */\n"
"    padding: 5px; /* Padding inside the input */\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formFrame = QtWidgets.QFrame(self.tab)
        self.formFrame.setMaximumSize(QtCore.QSize(16777215, 165))
        self.formFrame.setStyleSheet("background-color: rgba( 0, 0, 0, 75% );\n"
"    border-radius: 10px;")
        self.formFrame.setObjectName("formFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.formFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Browseline = QtWidgets.QLabel(self.formFrame)
        self.Browseline.setText("")
        self.Browseline.setObjectName("Browseline")
        self.gridLayout_2.addWidget(self.Browseline, 0, 1, 1, 2)
        self.Browse = QtWidgets.QPushButton(self.formFrame)
        self.Browse.setObjectName("Browse")
        self.gridLayout_2.addWidget(self.Browse, 0, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.scan = QtWidgets.QPushButton(self.formFrame)
        self.scan.setStyleSheet(" background-color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"color:black;")
        self.scan.setAutoDefault(False)
        self.scan.setDefault(False)
        self.scan.setFlat(False)
        self.scan.setObjectName("scan")
        self.horizontalLayout_2.addWidget(self.scan)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 3)
        self.gridLayout_3.addWidget(self.formFrame, 5, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 2)
        self.output = QtWidgets.QTextBrowser(self.tab)
        self.output.setMinimumSize(QtCore.QSize(0, 250))
        self.output.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.output.setObjectName("output")
        self.gridLayout_3.addWidget(self.output, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 1, 1, 1)
        self.input = QtWidgets.QTextEdit(self.tab)
        self.input.setObjectName("input")
        self.gridLayout_3.addWidget(self.input, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COMPILER_FIRST_STAGE"))
        self.Browse.setText(_translate("MainWindow", "Browse"))
        self.scan.setText(_translate("MainWindow", "SCAN"))
        self.label_2.setText(_translate("MainWindow", "INPUT"))
        self.label.setText(_translate("MainWindow", "SCANNER"))
        self.label_3.setText(_translate("MainWindow", "OUTPUT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Scanner"))
